<?php

namespace AppBundle\Repository;

/**
 * BookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookRepository extends \Doctrine\ORM\EntityRepository
{
	public function findForPage ($page)
    {
        return $this->getEntityManager()
            ->createQuery(
                //'SELECT book FROM AppBundle:Book book LIMIT $page * 18, ($page+1) * 18'
                'SELECT book FROM AppBundle:Book book'
            )
            -> setFirstResult($page*18)
            ->setMaxResults(18)
            ->getResult();
    }

    public function getNumberOfBooks()
    {
    	$query = $this->getEntityManager()
            ->createQuery(
                //'SELECT book FROM AppBundle:Book book LIMIT $page * 18, ($page+1) * 18'
                'SELECT book FROM AppBundle:Book book'
            )
            ->getResult();

        $total = count($query);

        return $total;
    }
}
