<?php

namespace AppBundle\Repository;

/**
 * Book_UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Book_UserRepository extends \Doctrine\ORM\EntityRepository
{
}
