<?php

namespace AppBundle\Repository;

/**
 * DateBorrowedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateBorrowedRepository extends \Doctrine\ORM\EntityRepository
{
}
