<?php

namespace UserBundle\Repository;
use UserBundle\User;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findForUsers1 ($page)
    {
        return $this->getEntityManager()
            ->createQuery(
                //'SELECT book FROM AppBundle:Book book LIMIT $page * 18, ($page+1) * 18'
                'SELECT user FROM UserBundle:User user'
            )
            -> setFirstResult($page*15)
            ->setMaxResults(15)
            ->getResult();
    }


public function findForUsers ($page,$enable)
   {
     $qb = $this->_em->createQueryBuilder();
         $qb = $this->_em->createQueryBuilder();
$qb->select('u')
->from('UserBundle:User', 'u')
->where('u.enabled = :enabled')
-> setFirstResult($page*15)
->setParameter('enabled', $enable)
->setMaxResults(15);
return $qb->getQuery()
->getResult();
    }
 


    public function getNumberOfUsers()
    {
        $query = $this->getEntityManager()
            ->createQuery(
                //'SELECT book FROM AppBundle:Book book LIMIT $page * 18, ($page+1) * 18'
                'SELECT user FROM UserBundle:User user WHERE user.enabled= false'
            )
            ->getResult();

        $total = count($query);

        return $total;
    }
}
