<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Book_User extends \AppBundle\Entity\Book_User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'book', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'dateRequested', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'datesBorrowed', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'dateReturned', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'dueDate', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'delay'];
        }

        return ['__isInitialized__', 'id', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'book', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'user', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'dateRequested', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'datesBorrowed', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'dateReturned', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'dueDate', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'status', '' . "\0" . 'AppBundle\\Entity\\Book_User' . "\0" . 'delay'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Book_User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setDateRequested($dateRequested)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateRequested', [$dateRequested]);

        return parent::setDateRequested($dateRequested);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateRequested()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateRequested', []);

        return parent::getDateRequested();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateReturned($dateReturned)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateReturned', [$dateReturned]);

        return parent::setDateReturned($dateReturned);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateReturned()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateReturned', []);

        return parent::getDateReturned();
    }

    /**
     * {@inheritDoc}
     */
    public function setDueDate($dueDate)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDueDate', [$dueDate]);

        return parent::setDueDate($dueDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getDueDate()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDueDate', []);

        return parent::getDueDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setBook(\AppBundle\Entity\Book $book)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBook', [$book]);

        return parent::setBook($book);
    }

    /**
     * {@inheritDoc}
     */
    public function getBook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBook', []);

        return parent::getBook();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser(\UserBundle\Entity\User $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        return parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addDatesBorrowed(\AppBundle\Entity\DateBorrowed $datesBorrowed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDatesBorrowed', [$datesBorrowed]);

        return parent::addDatesBorrowed($datesBorrowed);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDatesBorrowed(\AppBundle\Entity\DateBorrowed $datesBorrowed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDatesBorrowed', [$datesBorrowed]);

        return parent::removeDatesBorrowed($datesBorrowed);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatesBorrowed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatesBorrowed', []);

        return parent::getDatesBorrowed();
    }

    /**
     * {@inheritDoc}
     */
    public function setDelay($delay)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDelay', [$delay]);

        return parent::setDelay($delay);
    }

    /**
     * {@inheritDoc}
     */
    public function getDelay()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDelay', []);

        return parent::getDelay();
    }

}
